# Generated by Django 4.0 on 2023-07-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='OneWheel', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='OneWheel', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=250)),
                ('qantity', models.IntegerField(default=1)),
                ('description', models.TextField(default='No Description Given')),
                ('price', models.FloatField(default=0)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.category')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.model')),
            ],
        ),
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=100)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('profile_picture', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrailReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField(default='No Review Given')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.trail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=5)),
                ('review', models.TextField(default='No Review Given')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.user')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=250)),
                ('description', models.TextField(default='No Description Given')),
                ('members', models.ManyToManyField(blank=True, to='onewheeloneride.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default='No Comment Given')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.user')),
            ],
        ),
    ]
