# Generated by Django 4.0 on 2023-07-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onewheeloneride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
