# Generated by Django 4.2.3 on 2023-07-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onewheeloneride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.user')),
            ],
        ),
        migrations.CreateModel(
            name='TrailReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('trail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.trail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onewheeloneride.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
