# Generated by Django 4.0 on 2023-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onewheeloneride', '0002_productreview_trailreview_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='OneWheel', max_length=100),
        ),
        migrations.AddField(
            model_name='model',
            name='name',
            field=models.CharField(default='OneWheel', max_length=100),
        ),
    ]
