# Generated by Django 4.0 on 2023-07-25 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onewheeloneride', '0006_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
