# Generated by Django 4.0 on 2023-07-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onewheeloneride', '0007_remove_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='picture',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='trail',
            name='picture',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(max_length=250),
        ),
    ]
