# Generated by Django 4.0 on 2023-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onewheeloneride', '0008_alter_group_picture_alter_trail_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user_id',
        ),
        migrations.AddField(
            model_name='group',
            name='user_id',
            field=models.ManyToManyField(through='onewheeloneride.User', to='onewheeloneride.Group'),
        ),
    ]
